package com.aws.lambda.user.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.AllArgsConstructor;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Min;
import javax.validation.constraints.Max;
import java.time.LocalDateTime;

/**
 * User entity representing a user in the system.
 * Contains user profile information with validation constraints.
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "User")
public class User {

    @DynamoDBHashKey(attributeName = "uuid")
    @DynamoDBAutoGeneratedKey
    private String uuid;

    @NotBlank(message = "Name is required")
    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @Email(message = "Email should be valid")
    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @NotNull(message = "Age is required")
    @Min(value = 18, message = "Age must be at least 18")
    @Max(value = 120, message = "Age must be at most 120")
    @DynamoDBAttribute(attributeName = "age")
    private Integer age;

    @DynamoDBAttribute(attributeName = "department")
    private String department;

    @DynamoDBAttribute(attributeName = "role")
    private String role;

    @DynamoDBAttribute(attributeName = "createdAt")
    private LocalDateTime createdAt;

    @DynamoDBAttribute(attributeName = "updatedAt")
    private LocalDateTime updatedAt;

    @DynamoDBAttribute(attributeName = "isActive")
    private Boolean isActive;

    @DynamoDBAttribute(attributeName = "phoneNumber")
    private String phoneNumber;

}
